project:
  type: book

book:
  title: REDCap Style Guide
  author: The Research Support Core at the Center for Healthy Minds, UW-Madison
  copyright:
    holder: Board of Regents of the University of Wisconsin System
    year: 2025

  site-url: https://uwmadison-chm.github.io/redcap-style
  repo-url: https://github.com/uwmadison-chm/redcap-style
  repo-branch: main
  repo-actions: [source, issue]

  chapters:
  - index.qmd

format:
  html:
    callout-appearance: simple
    theme:
      - styles.scss
