# Welcome {-}

(This is temporary and aspirational, useful content should arrive soon.)

The size and complexity of research projects you can take on depends on a lot of things — one of the most important is how you organize your database. REDCap can be used to run incredibly complex studies; your experience will be so much easier if you use a consistent style throughout. And while many of REDCap's features are documented, there is basically no official guide on how you _should_ set things up.

This guide reflects how we build studies at the [Center for Healthy Minds](https://centerhealthyminds.org). It's primarily for our researchers, but everyone is free to use it. You may disagree with some of the guidelines here (style guides are, after all, opinionated!), but if you take one thing from this guide: **Choose a consistent style and use it as much as you can in your own project.**

The more consistent you are within your project, the less you'll need to refer to your codebooks, look up variable names, and the fewer logic errors you'll make. The more consistent you are, the easier time participants will have in understanding and following your protocol.

Additionally: Take this guide as a set of recommendations, not hard-and-fast rules. If there's ever a conflict between this guide and doing science the right way, absolutely do the science.

This guide owes a great deal, both in structure and its opinionated nature, to the excellent [Tidyverse style guide](https://style.tidyverse.org). Kudos to that team for a great resource.

If you find errors, inconsistencies, or typos, please file a note on our [Issues page](https://github.com/uwmadison-chm/redcap-style/issues). If you have ideas, disagreements, or anything else, use the [Discussions section](https://github.com/uwmadison-chm/redcap-style/discussions).